name: Renovate

on:
  workflow_call:
    inputs:
      logLevel:
        description: "Override default log level"
        required: false
        default: "info"
        type: string
      overrideSchedule:
        description: "Override all schedules"
        required: false
        default: "false"
        type: string
  schedule:
    - cron: '0 0 * * 0'  # This runs the workflow every Sunday at midnight
  push:
    branches:
      - main
  pull_request:
      branches:
        - main
    
jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.MEND_RNV_GITHUB_APP_ID }}
          private-key: ${{ secrets.MEND_RNV_GITHUB_APP_KEY }}

      - name: Run Renovate
        run: |
          docker run --rm \
            --volume ./renovate.json:/usr/src/app/renovate.json \
            --env LOG_LEVEL=debug \
            --env RENOVATE_TOKEN="${{ steps.app-token.outputs.token }}" \
            ghcr.io/renovatebot/renovate:latest