name: Renovate

on:
  workflow_call:
    inputs:
      logLevel:
        description: "Override default log level"
        required: false
        default: "info"
        type: string
      overrideSchedule:
        description: "Override all schedules"
        required: false
        default: "false"
        type: string
  schedule:
    - cron: '0 0 * * 0'  # This runs the workflow every Sunday at midnight
  push:
    branches:
      - main
  pull_request:
      branches:
        - main
    
jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.MEND_RNV_GITHUB_APP_ID }}
          private-key: ${{ secrets.MEND_RNV_GITHUB_APP_KEY }}

      - name: Run Renovate
        run: |
          docker run --rm \
            --volume ./config.js:/usr/src/app/config.js \
            --env LOG_LEVEL=debug \
            --env RENOVATE_TOKEN="${{ steps.app-token.outputs.token }}" \
            ghcr.io/renovatebot/renovate:latest